steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/radiofodder-live/radiofodder-backend-docker/radiofodder-image:tag5', '.']

images:
- 'us-west2-docker.pkg.dev/radiofodder-live/radiofodder-backend-docker/radiofodder-image:tag5'